INSERT INTO pracownicy (IMIE,NAZWISKO,SPECJALIZACJA,ZACHOWANIE,id_szefa) VALUES
 ('Michal','Naizdup','CZYSCICIEL',"KULTYSTA",1),
 ('Ben','Arames','TECHNIK SEDESOWY',"MIESO ARMATNIE",5),
 ('Marian','Pazdzioch','TECHNIK SEDESOWY',"WIERNY SLUGA",6),
 ('Jon','Szwaw','SPECJALISTA WYWIADU',"MIESO ARMATNIE",5),
 ('RYSIEK','KLANOWY','TECHNIK SEDESOWY',"MIESO ARMATNIE",5),
('Michael','Naizdup','CZYSCICIEL',"MIESO ARMATNIE",2),
 ('Edzio','listonosz','TECHNIK SEDESOWY',"KULTYSTA",3),
 ('Jon','Szwaw','SPECJALISTA WYWIADU',"MIESO ARMATNIE",5),
 ('RYSIEK','KLANOWY','TECHNIK SEDESOWY',"WIERNY SLUGA",6),
('Michael','Naizdup',"SPECJALISTA WYWIADU","MIESO ARMATNIE",8);