CREATE TABLE PANOWIE(
	id_pana INT auto_increment PRIMARY KEY,
	IMIE VARCHAR(69),
	NAZWISKO VARCHAR(255),
    LOJALNOSC ENUM("NIEZACHWIANA","TENDENCJA DO ZDRADY"),
	ROLA  ENUM("PAN PANÓW","EGZEKUTOR","STARSZY KIBLOWY","BANKIER" ),id_kosmity int ,FOREIGN KEY(id_kosmity)REFERENCES kosmici(id_kosmity)
	);