 CREATE TABLE pracownicy (
  id_pracownika INT auto_increment PRIMARY KEY,
  IMIE VARCHAR(67),
  NAZWISKO VARCHAR(77),
  SPECJALIZACJA ENUM(
    "CZYSCICIEL",
    "SPECJALISTA WYWIADU",
    "TECHNIK SEDESOWY"
  ), ZACHOWANIE ENUM("WIERNY SŁUGA","MIESO ARMATNIE","KULTYSTA"),id_szefa int ,FOREIGN KEY(id_szefa)REFERENCES sludzy(id_szefa));